version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: basics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

